2067793587
정자푸르지오시티3차
20.12.03.
2020/12/03 22:10:07
Traceback (most recent call last):
  File "naver_land.py", line 80, in <module>
    check_jungja()
  File "naver_land.py", line 78, in check_jungja
    threading.Timer(1800, main).start()
NameError: global name 'main' is not defined
2067793587
정자푸르지오시티3차
20.12.03.
2020/12/03 22:10:55
2067793587
정자푸르지오시티3차
20.12.03.
2020/12/03 22:18:32
ERROR:root:invalid status: 307
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 1075, in run
    self.function(*self.args, **self.kwargs)
  File "naver_land.py", line 50, in check_jungja
    data = json.loads(resp.text)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2067793587
정자푸르지오시티3차
20.12.03.
2020/12/03 23:00:07
